### PR TITLE
[skip ci] Add link to spack.yaml instructions

### PR DESCRIPTION
**Pull request by anton-seaice**

### CODE REVIEW

**Comment by chrisb13** [comment]
Thanks. I've also crossed off [here](https://forum.access-hive.org.au/t/ocean-team-workshop-12-15th-november-2024/3857/7?u=cbull)

**Comment by anton-seaice** [comment]
I think you pressured the wrong button @chrisb13 :-)

**Comment by anton-seaice** [comment]
Can you please go to the Files changed tab and select Review Changes and hopefully 'Approve'

**Review by chrisb13 — APPROVED** [review]

**Comment by chrisb13** [comment]
> I think you pressed the wrong button @chrisb13 :-)

Sorry about that! All good now I hope?

**Comment by anton-seaice** [comment]
@CodeGat - Can you merge this please ? Its a docs only update

**Comment by CodeGat** [comment]
Done @anton-seaice - I also removed the required prerelease deployment check because I hadn't standardized that across the repositories yet and don't know if we should.

**Pull request merged**
